### ISSUE TITLE
Possibility to remove system jar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IvanVolosyuk/diskusage#19]
```
You may be aware that f-droid.org distributes this app. It was included in the 
early days when inclusion criteria was less strict and libraries that couldn't 
be built were allowed. System.jar is derived from AOSP so it can't be built by 
f-droid. Are there any plans to remove it?

```

Original issue reported on code.google.com by `david8bl...@gmail.com` on 28 Jan 2013 at 11:54

**Comment by IvanVolosyuk** [comment]
I use some of hidden android APIs. I found the only way how to compile the app with the hidden apis. The jar is not supposed to be included in build binary.

**Comment by ParkerK** [comment]
Looks like it's been removed now, should this be closed?

**Comment by PanderMusubi** [comment]
According to https://gitlab.com/fdroid/fdroiddata/issues/977#note_193904793 this prebuild jar is still included or is reincluded by a newer version. Please reinvestigate and fix this issue (again) so the latest version can be build for F-Droid.

**Comment by IvanVolosyuk** [comment]
Removed in master.
