### ISSUE TITLE
Sparse file support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [IvanVolosyuk/diskusage#30]
```
Request:
Please support sparse files by reporting both apparent and allocated file sizes.

Some smartphones use filesystems which support sparse files.  The diskusage app 
only appears to report the apparent file sizes.  One such phone is the Motorola 
Moto X which uses the F2FS filesystem on the data partition.
```

Original issue reported on code.google.com by `argov...@gmail.com` on 1 Jul 2014 at 8:48

**Comment by IvanVolosyuk** [comment]
Sparse files are supported, but I guess it was broken for a while. I found out this breakage just now. Will update app soon with the fix.

**Comment by IvanVolosyuk** [comment]
3.8.0 should have sparse file supported on arm devices.
