### ISSUE TITLE
Update F-Droid 

### ISSUE THREAD

**Issue by homersimpsons** [IvanVolosyuk/diskusage#38]
Hi, on F-Droid the last update is from 2013, please update this

**Comment by IvanVolosyuk** [comment]
I don't update there. They used to build themselves.

**Comment by ildar** [comment]
Sure. But please create git tags for releases. That's necessary for f-droid
builds. Please?

**Comment by mvdan** [comment]
FWIW, we would have built a newer version if we knew how to build `assets/scan5`. There are no build instructions.

**Comment by IvanVolosyuk** [comment]
Good point. Both scan binaries was build from same sources, but one build
with old ndk tool chain, another with new one. Android seem like introduced
a requirement for binaries to use PIC and my old binary didn't work anymore
with newer versions of Android, but binary build with new tool chain didn't
work on older Android versions. It looks like I misunderstand something,
but i didn't have time to figure this out. Patches are welcome to clean up
this mess.

**Comment by mvdan** [comment]
Oh, I see. What NDK version did you use for each?

**Comment by IvanVolosyuk** [comment]
I'm not sure. Current for each time I built the binary.

**Comment by IvanVolosyuk** [comment]
"Scan5" is build with current sdk for the time of
https://github.com/IvanVolosyuk/diskusage/commit/3fc4575eb27ee1f5ad3528202c6c71a74be29c57
March 2, 2015

"Scan" is build with the current sdk for the time of
296d3317a49d3a506609fb24056aee75957bd64c
May 13, 2011

**Comment by ildar** [comment]
@mvdan, possible to build it with current NDK?

**Comment by ildar** [comment]
>
> @mvdan, possible to build it with current NDK?
>

Also, @IvanVolosyuk , will the Java part work if only the current `Scan`
(built from source) is available?

**Comment by ildar** [comment]
приём?

**Comment by mvdan** [comment]
I'm no longer involved in F-Droid; if you want help, try the fdroiddata issue tracker or IRC.

**Comment by ildar** [comment]
ah! ok.
Ivan, do you think the DiskUsage has any chance for successful build in
F-Droid environment? With one Scan binary?

**Comment by Bubu** [comment]
Build and publsihed on f-droid thanks to https://gitlab.com/fdroid/fdroiddata/merge_requests/2499

**Comment by PanderMusubi** [comment]
Thanks for the new release. Can someone please close this?
