### ISSUE TITLE
Visual structure glitches

### ISSUE THREAD

**Issue by BangDroid** [IvanVolosyuk/diskusage#40]
Visual structure glitches when zooming on large subdirectory trees.
Can be seen: https://drive.google.com/file/d/0B4EXjCHMjl3JQ1FNRjVPRDRZaTg/view?usp=drivesdk

**Comment by IvanVolosyuk** [comment]
I know about it. It has to do with the way how DiskUsage represents data
internally. It was design decision for slight performance optimization on
old devices. I guess now the devices are fast enough and this can be fixed.

**Comment by IvanVolosyuk** [comment]
Should be fixed on 3.8.0
