### ISSUE TITLE
Support Amaze file manager

### ISSUE THREAD

**Issue by PanderMusubi** [IvanVolosyuk/diskusage#42]
Please support also https://github.com/arpitkh96/AmazeFileManager as file manager

**Comment by IvanVolosyuk** [comment]
Here is how DiskUsage gets file managers:
https://github.com/IvanVolosyuk/diskusage/blob/master/app/src/main/java/com/google/android/diskusage/DiskUsage.java#L300
Ask developers of the file manager to support this Intent. Thanks.

**Comment by PanderMusubi** [comment]
Thanks. Reported here https://github.com/TeamAmaze/AmazeFileManager/issues/791
