### ISSUE TITLE
No viewer found

### ISSUE THREAD

**Issue by diegodlh** [IvanVolosyuk/diskusage#53]
I've been using DiskUsage for a long time as it is a very simple, lightweight yet complete and useful app. For the same reason, I've also been using Total Commander as my favorite file manager. However, for some reason DiskUsage doesn't seem to be able to "show" directories with this file manager, and instead pops up a "No viewer found" error message.
I don't know were to start from to solve this and I would really appreciate it if you could guide me. In the past I used ES File Explorer and it worked OK with it, but it has become very large and cumbersome for my rather old cell phone.
Thank you

**Comment by ildar** [comment]
This is similar to
https://github.com/IvanVolosyuk/diskusage/issues/42#issuecomment-333347571
This app does everything right and doesn't need to be modified. File
managers have to implement some Android intents. Amaze FM is doing that
AFAIK.

**Comment by diegodlh** [comment]
Thank you for replying. Sorry for the noise
