### ISSUE TITLE
Folder size not displayed correct 

### ISSUE THREAD

**Issue by Maroko** [IvanVolosyuk/diskusage#61]
The .thumbnail folder is showing only 122 MB, even though in it is a 5 GB file.

![photo_2019-08-15_00-36-30](https://user-images.githubusercontent.com/6225156/63061296-f00a1100-bef4-11e9-9ebe-137a99094bf0.jpg)
![photo_2019-08-15_00-36-32](https://user-images.githubusercontent.com/6225156/63061299-f39d9800-bef4-11e9-9ae0-2039c5b4116c.jpg)

**Comment by IvanVolosyuk** [comment]
This is a sparse file. https://en.wikipedia.org/wiki/Sparse_file
The length of the file is 5 GB, but actually allocated block are much less.
Did you question yourself, how come thumbnails use 5 GB? Isn't it too much?
