### ISSUE TITLE
App is no longer available on Google Play

### ISSUE THREAD

**Issue by quietsamurai98** [IvanVolosyuk/diskusage#63]
The old [app page](https://play.google.com/store/apps/details?id=com.google.android.diskusage) now shows a generic "Not Found" page. This isn't strictly an issue with the code, but it certainly is an issue for usability as new users cannot download the app anymore.

**Comment by IvanVolosyuk** [comment]
I've got email from PlayStore where they claim I violated a certain
policy. I'm trying to resolve it, but it seems it either takes more
time or I'm kinda stuck, depends how I should look at it.

**Comment by IvanVolosyuk** [comment]
Restored on Play Store.
