### ISSUE TITLE
Space-invaders mode with points for storage recovery

### ISSUE THREAD

**Issue by topshef** [IvanVolosyuk/diskusage#71]
Firstly many thanks for this app.. for the first time in years my phone is below 99% internal memory storage!

So with such miracles comes a request for another.. every Android device needs this app, so how about blending in a space invaders mode (blast that bloated app out of your phone!) and with an option to earn real money by renting recovered storage space on some P2P system (IPFS?)

Any takers?

I'd happy to help setup a crowd-fund token to support this eg via https://gomint.co

**Comment by TehDomic** [comment]
Non-FOSS practices. Please close this issue @IvanVolosyuk.

**Comment by IvanVolosyuk** [comment]
Lol
