### ISSUE TITLE
not compatible with Android 14

### ISSUE THREAD

**Issue by eylenburg** [IvanVolosyuk/diskusage#84]
Due to a minimum API required by Google

**Comment by jahway603** [comment]
I'm having the same issue on a new phone when trying to install this from F-Droid and taking that APK and attempting to install from the CLI using adb...

```
$ adb install "com.google.android.diskusage_v3080.apk"
Performing Streamed Install
adb: failed to install com.google.android.diskusage_v3080.apk: Failure [INSTALL_FAILED_DEPRECATED_SDK_VERSION: App package must target at least SDK version 23, but found 19]
```

This doesn't make sense as https://github.com/IvanVolosyuk/diskusage/blob/master/app/build.gradle#L10 shows us the target SDK is 30 -- not 19...

**Comment by jahway603** [comment]
@eylenburg if you clone this repo and build it yourself, then it works fine on Android 14. I submitted a F-Droid forum post about getting this updated on F-Droid here https://forum.f-droid.org/t/please-update-app-diskusage-to-support-android-14/24364

**Comment by jahway603** [comment]
@IvanVolosyuk can you please add a release tag for v 4.0.2? I think F-Droid may need a tag to build from.

**Comment by IvanVolosyuk** [comment]
That's never been a problem for them. I created it anyway.

**Comment by linsui** [comment]
Right, tag is not required for build. It's for autoupdate only. And since there was no tag, the autoupdate is not enabled. And we didn't update it for a long time due to https://github.com/IvanVolosyuk/diskusage/issues/19.

**Comment by IvanVolosyuk** [comment]
Removed the system.jar it was needed for build time linking to hidden APIs, which are not hidden anymore as far as I can see.

**Comment by linsui** [comment]
Thanks, it will be updated in few days. The first update in F-Droid in the past 6 years. :)

**Comment by CallMeLaNN** [comment]
Thanks for the update. I just tried with Android 13 (One UI) btw. Before update not working, after update it works.

Just one thing, it doesn't prompt to access "All files access" just access denied to ext storage. Music & Photo automatically allowed. I enable the all files access manually from settings.

**Comment by eylenburg** [comment]
Nice, I can install it from F-Droid now. Thank you @IvanVolosyuk

**Comment by Herve5** [comment]
(this new version of DiskUsage just published on F-Droid fails in accessing the external card on my phone (while the previous one did it)...
_'Access to external storage has been denied'_
-now solved thanks to @linsui below!)

**Comment by linsui** [comment]
> Just one thing, it doesn't prompt to access "All files access" just access denied to ext storage. Music & Photo automatically allowed. I enable the all files access manually from settings.

**Comment by Herve5** [comment]
@linsui excellent, thank you!
