### ISSUE TITLE
cannot read apps

### ISSUE THREAD

**Issue by Hanxyz13** [IvanVolosyuk/diskusage#98]
Hi, this diskusage can't read apps, it categorises them into system data, but reads media files fine!
Version:5.0-alpha1, Android 13, rooted
![Screenshot_2024-03-11-12-28-25-121_com google android diskusage](https://github.com/IvanVolosyuk/diskusage/assets/113858346/56058f3f-7944-4286-ad18-36acf323ee1c)

**Comment by IvanVolosyuk** [comment]
There should be a permission dialog to get access to installed apps. Try uninstalling and installing again to trigger it. Next time it runs it should ask for permission to get app usage info.

**Comment by Hanxyz13** [comment]
> There should be a permission dialog to get access to installed apps. Try uninstalling and installing again to trigger it. Next time it runs it should ask for permission to get app usage info.

oh,when I tried uninstalling and reinstalling, the problem persisted, but I finally found the permission and turned it on and was finally able to access the app, thanks!![Screenshot_2024-03-11-19-58-28-857_com.android.settings.jpg](https://github.com/IvanVolosyuk/diskusage/assets/113858346/3b5b5adf-7945-4ba1-b2b9-f10266cef36a)
